stats_categorical
fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten pull request #46
Opened 2023-02-23 11:05 UTC by WlanNergady

stats_categorical enthält jetzt Häufigkeitstabellen, Barplots dazu und den jeweiligen Modus.

2023-02-23 21:25 UTC, PhilippSL reviewed
Der Code funktioniert bei mir gut, Umlaute sollten eher vermieden werden, vielleicht noch eine Erklärung des Arguments (mit @param) und ein usage example ergänzen

2023-02-24 23:44 UTC, danfleon requested changes
@WlanNergady, ich habe dir in #38 geschrieben, sorry für die verspätete Antwort da. Eine Entropie-Berechnung könntest du nach dem Frequenz-Berechnung auch so machen: 

`-sum(freq * log2(freq))`

Zusätzlich könntest du auch eine Überprüfung machen, ob die Variable kategorisch ist. Was denkst du?

2023-02-25 14:56 UTC, WlanNergady commented
Überprüfung, ob die Variable kategorisch ist bzw. Entfernung, wenn sie es nicht ist, halte ich für eine sehr gute Idee, ich muss nur noch schauen, wie ich es hinkriege.

2023-02-26 17:34 UTC, WlanNergady commented
Ich hab jetzt die Filterung nach kategoriellen Variablen hinzugefügt, damit ist die Funktion fertig. Ihr könnt das nochmal überprüfen, wenn ihr wollt, und dann mergen, ich mach schonmal mit der anderen Funktion weiter.

2023-02-26 18:28 UTC, danfleon approved these changes

2023-02-26 18:28 UTC, merged